name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: install & build
        run: |
          npm i
          npm run build:release

      - name: archive
        run: |
          cd build
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "ARCHIVE_NAME=${TAG_NAME}.tar.gz" >> $GITHUB_ENV
          tar -czf ../${{ env.ARCHIVE_NAME }} * .??*
          cd ..
